FROM debian:stable
LABEL maintainer="Joe Moore <jpvlsmv@gmail.com>"

RUN apt-get update && apt-get install -y make binutils build-essential gcc g++ patch perl python3 unzip rsync file bc wget git asciidoc w3m dblatex graphviz python3-matplotlib
RUN find ~
